apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: default
  name: l2discovery
  labels:
    tier: node
    app: l2discovery
spec:
  selector:
    matchLabels:
      name: l2discovery
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        tier: node
        app: l2discovery
        name: l2discovery
    spec:
      hostNetwork: true
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 300
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 300
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      containers:
      - name: l2discovery
        imagePullPolicy: Always
        securityContext:
          privileged: true
          runAsUser: 0
        image: quay.io/testnetworkfunction/l2discovery:latest
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "100m"
